// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: machinetalk/protobuf/nanopb.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "machinetalk/protobuf/nanopb.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* NanoPBOptions_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  NanoPBOptions_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* FieldType_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* IntSize_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_machinetalk_2fprotobuf_2fnanopb_2eproto() {
  protobuf_AddDesc_machinetalk_2fprotobuf_2fnanopb_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "machinetalk/protobuf/nanopb.proto");
  GOOGLE_CHECK(file != NULL);
  NanoPBOptions_descriptor_ = file->message_type(0);
  static const int NanoPBOptions_offsets_[9] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NanoPBOptions, max_size_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NanoPBOptions, max_count_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NanoPBOptions, int_size_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NanoPBOptions, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NanoPBOptions, long_names_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NanoPBOptions, packed_struct_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NanoPBOptions, skip_message_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NanoPBOptions, no_unions_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NanoPBOptions, msgid_),
  };
  NanoPBOptions_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      NanoPBOptions_descriptor_,
      NanoPBOptions::default_instance_,
      NanoPBOptions_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NanoPBOptions, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NanoPBOptions, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(NanoPBOptions));
  FieldType_descriptor_ = file->enum_type(0);
  IntSize_descriptor_ = file->enum_type(1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_machinetalk_2fprotobuf_2fnanopb_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    NanoPBOptions_descriptor_, &NanoPBOptions::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_machinetalk_2fprotobuf_2fnanopb_2eproto() {
  delete NanoPBOptions::default_instance_;
  delete NanoPBOptions_reflection_;
}

void protobuf_AddDesc_machinetalk_2fprotobuf_2fnanopb_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::protobuf_AddDesc_google_2fprotobuf_2fdescriptor_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n!machinetalk/protobuf/nanopb.proto\032 goo"
    "gle/protobuf/descriptor.proto\"\200\002\n\rNanoPB"
    "Options\022\020\n\010max_size\030\001 \001(\005\022\021\n\tmax_count\030\002"
    " \001(\005\022&\n\010int_size\030\007 \001(\0162\010.IntSize:\nIS_DEF"
    "AULT\022$\n\004type\030\003 \001(\0162\n.FieldType:\nFT_DEFAU"
    "LT\022\030\n\nlong_names\030\004 \001(\010:\004true\022\034\n\rpacked_s"
    "truct\030\005 \001(\010:\005false\022\033\n\014skip_message\030\006 \001(\010"
    ":\005false\022\030\n\tno_unions\030\010 \001(\010:\005false\022\r\n\005msg"
    "id\030\t \001(\r*Z\n\tFieldType\022\016\n\nFT_DEFAULT\020\000\022\017\n"
    "\013FT_CALLBACK\020\001\022\016\n\nFT_POINTER\020\004\022\r\n\tFT_STA"
    "TIC\020\002\022\r\n\tFT_IGNORE\020\003*D\n\007IntSize\022\016\n\nIS_DE"
    "FAULT\020\000\022\010\n\004IS_8\020\010\022\t\n\005IS_16\020\020\022\t\n\005IS_32\020 \022"
    "\t\n\005IS_64\020@:E\n\016nanopb_fileopt\022\034.google.pr"
    "otobuf.FileOptions\030\362\007 \001(\0132\016.NanoPBOption"
    "s:G\n\rnanopb_msgopt\022\037.google.protobuf.Mes"
    "sageOptions\030\362\007 \001(\0132\016.NanoPBOptions:E\n\016na"
    "nopb_enumopt\022\034.google.protobuf.EnumOptio"
    "ns\030\362\007 \001(\0132\016.NanoPBOptions:>\n\006nanopb\022\035.go"
    "ogle.protobuf.FieldOptions\030\362\007 \001(\0132\016.Nano"
    "PBOptionsB\032\n\030fi.kapsi.koti.jpa.nanopb", 797);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "machinetalk/protobuf/nanopb.proto", &protobuf_RegisterTypes);
  NanoPBOptions::default_instance_ = new NanoPBOptions();
  ::google::protobuf::internal::ExtensionSet::RegisterMessageExtension(
    &::google::protobuf::FileOptions::default_instance(),
    1010, 11, false, false,
    &::NanoPBOptions::default_instance());
  ::google::protobuf::internal::ExtensionSet::RegisterMessageExtension(
    &::google::protobuf::MessageOptions::default_instance(),
    1010, 11, false, false,
    &::NanoPBOptions::default_instance());
  ::google::protobuf::internal::ExtensionSet::RegisterMessageExtension(
    &::google::protobuf::EnumOptions::default_instance(),
    1010, 11, false, false,
    &::NanoPBOptions::default_instance());
  ::google::protobuf::internal::ExtensionSet::RegisterMessageExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    1010, 11, false, false,
    &::NanoPBOptions::default_instance());
  NanoPBOptions::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_machinetalk_2fprotobuf_2fnanopb_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_machinetalk_2fprotobuf_2fnanopb_2eproto {
  StaticDescriptorInitializer_machinetalk_2fprotobuf_2fnanopb_2eproto() {
    protobuf_AddDesc_machinetalk_2fprotobuf_2fnanopb_2eproto();
  }
} static_descriptor_initializer_machinetalk_2fprotobuf_2fnanopb_2eproto_;
const ::google::protobuf::EnumDescriptor* FieldType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return FieldType_descriptor_;
}
bool FieldType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* IntSize_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return IntSize_descriptor_;
}
bool IntSize_IsValid(int value) {
  switch(value) {
    case 0:
    case 8:
    case 16:
    case 32:
    case 64:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#ifndef _MSC_VER
const int NanoPBOptions::kMaxSizeFieldNumber;
const int NanoPBOptions::kMaxCountFieldNumber;
const int NanoPBOptions::kIntSizeFieldNumber;
const int NanoPBOptions::kTypeFieldNumber;
const int NanoPBOptions::kLongNamesFieldNumber;
const int NanoPBOptions::kPackedStructFieldNumber;
const int NanoPBOptions::kSkipMessageFieldNumber;
const int NanoPBOptions::kNoUnionsFieldNumber;
const int NanoPBOptions::kMsgidFieldNumber;
#endif  // !_MSC_VER

NanoPBOptions::NanoPBOptions()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:NanoPBOptions)
}

void NanoPBOptions::InitAsDefaultInstance() {
}

NanoPBOptions::NanoPBOptions(const NanoPBOptions& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:NanoPBOptions)
}

void NanoPBOptions::SharedCtor() {
  _cached_size_ = 0;
  max_size_ = 0;
  max_count_ = 0;
  int_size_ = 0;
  type_ = 0;
  long_names_ = true;
  packed_struct_ = false;
  skip_message_ = false;
  no_unions_ = false;
  msgid_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

NanoPBOptions::~NanoPBOptions() {
  // @@protoc_insertion_point(destructor:NanoPBOptions)
  SharedDtor();
}

void NanoPBOptions::SharedDtor() {
  if (this != default_instance_) {
  }
}

void NanoPBOptions::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* NanoPBOptions::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return NanoPBOptions_descriptor_;
}

const NanoPBOptions& NanoPBOptions::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_machinetalk_2fprotobuf_2fnanopb_2eproto();
  return *default_instance_;
}

NanoPBOptions* NanoPBOptions::default_instance_ = NULL;

NanoPBOptions* NanoPBOptions::New() const {
  return new NanoPBOptions;
}

void NanoPBOptions::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<NanoPBOptions*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 255) {
    ZR_(max_size_, type_);
    ZR_(packed_struct_, no_unions_);
    long_names_ = true;
  }
  msgid_ = 0u;

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool NanoPBOptions::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:NanoPBOptions)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 max_size = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &max_size_)));
          set_has_max_size();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_max_count;
        break;
      }

      // optional int32 max_count = 2;
      case 2: {
        if (tag == 16) {
         parse_max_count:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &max_count_)));
          set_has_max_count();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_type;
        break;
      }

      // optional .FieldType type = 3 [default = FT_DEFAULT];
      case 3: {
        if (tag == 24) {
         parse_type:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::FieldType_IsValid(value)) {
            set_type(static_cast< ::FieldType >(value));
          } else {
            mutable_unknown_fields()->AddVarint(3, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_long_names;
        break;
      }

      // optional bool long_names = 4 [default = true];
      case 4: {
        if (tag == 32) {
         parse_long_names:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &long_names_)));
          set_has_long_names();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_packed_struct;
        break;
      }

      // optional bool packed_struct = 5 [default = false];
      case 5: {
        if (tag == 40) {
         parse_packed_struct:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &packed_struct_)));
          set_has_packed_struct();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_skip_message;
        break;
      }

      // optional bool skip_message = 6 [default = false];
      case 6: {
        if (tag == 48) {
         parse_skip_message:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &skip_message_)));
          set_has_skip_message();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(56)) goto parse_int_size;
        break;
      }

      // optional .IntSize int_size = 7 [default = IS_DEFAULT];
      case 7: {
        if (tag == 56) {
         parse_int_size:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::IntSize_IsValid(value)) {
            set_int_size(static_cast< ::IntSize >(value));
          } else {
            mutable_unknown_fields()->AddVarint(7, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(64)) goto parse_no_unions;
        break;
      }

      // optional bool no_unions = 8 [default = false];
      case 8: {
        if (tag == 64) {
         parse_no_unions:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &no_unions_)));
          set_has_no_unions();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(72)) goto parse_msgid;
        break;
      }

      // optional uint32 msgid = 9;
      case 9: {
        if (tag == 72) {
         parse_msgid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &msgid_)));
          set_has_msgid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:NanoPBOptions)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:NanoPBOptions)
  return false;
#undef DO_
}

void NanoPBOptions::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:NanoPBOptions)
  // optional int32 max_size = 1;
  if (has_max_size()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->max_size(), output);
  }

  // optional int32 max_count = 2;
  if (has_max_count()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->max_count(), output);
  }

  // optional .FieldType type = 3 [default = FT_DEFAULT];
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->type(), output);
  }

  // optional bool long_names = 4 [default = true];
  if (has_long_names()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->long_names(), output);
  }

  // optional bool packed_struct = 5 [default = false];
  if (has_packed_struct()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(5, this->packed_struct(), output);
  }

  // optional bool skip_message = 6 [default = false];
  if (has_skip_message()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(6, this->skip_message(), output);
  }

  // optional .IntSize int_size = 7 [default = IS_DEFAULT];
  if (has_int_size()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      7, this->int_size(), output);
  }

  // optional bool no_unions = 8 [default = false];
  if (has_no_unions()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(8, this->no_unions(), output);
  }

  // optional uint32 msgid = 9;
  if (has_msgid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(9, this->msgid(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:NanoPBOptions)
}

::google::protobuf::uint8* NanoPBOptions::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:NanoPBOptions)
  // optional int32 max_size = 1;
  if (has_max_size()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->max_size(), target);
  }

  // optional int32 max_count = 2;
  if (has_max_count()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->max_count(), target);
  }

  // optional .FieldType type = 3 [default = FT_DEFAULT];
  if (has_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->type(), target);
  }

  // optional bool long_names = 4 [default = true];
  if (has_long_names()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(4, this->long_names(), target);
  }

  // optional bool packed_struct = 5 [default = false];
  if (has_packed_struct()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(5, this->packed_struct(), target);
  }

  // optional bool skip_message = 6 [default = false];
  if (has_skip_message()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(6, this->skip_message(), target);
  }

  // optional .IntSize int_size = 7 [default = IS_DEFAULT];
  if (has_int_size()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      7, this->int_size(), target);
  }

  // optional bool no_unions = 8 [default = false];
  if (has_no_unions()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(8, this->no_unions(), target);
  }

  // optional uint32 msgid = 9;
  if (has_msgid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(9, this->msgid(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NanoPBOptions)
  return target;
}

int NanoPBOptions::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 max_size = 1;
    if (has_max_size()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->max_size());
    }

    // optional int32 max_count = 2;
    if (has_max_count()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->max_count());
    }

    // optional .IntSize int_size = 7 [default = IS_DEFAULT];
    if (has_int_size()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->int_size());
    }

    // optional .FieldType type = 3 [default = FT_DEFAULT];
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
    }

    // optional bool long_names = 4 [default = true];
    if (has_long_names()) {
      total_size += 1 + 1;
    }

    // optional bool packed_struct = 5 [default = false];
    if (has_packed_struct()) {
      total_size += 1 + 1;
    }

    // optional bool skip_message = 6 [default = false];
    if (has_skip_message()) {
      total_size += 1 + 1;
    }

    // optional bool no_unions = 8 [default = false];
    if (has_no_unions()) {
      total_size += 1 + 1;
    }

  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    // optional uint32 msgid = 9;
    if (has_msgid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->msgid());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void NanoPBOptions::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const NanoPBOptions* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const NanoPBOptions*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void NanoPBOptions::MergeFrom(const NanoPBOptions& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_max_size()) {
      set_max_size(from.max_size());
    }
    if (from.has_max_count()) {
      set_max_count(from.max_count());
    }
    if (from.has_int_size()) {
      set_int_size(from.int_size());
    }
    if (from.has_type()) {
      set_type(from.type());
    }
    if (from.has_long_names()) {
      set_long_names(from.long_names());
    }
    if (from.has_packed_struct()) {
      set_packed_struct(from.packed_struct());
    }
    if (from.has_skip_message()) {
      set_skip_message(from.skip_message());
    }
    if (from.has_no_unions()) {
      set_no_unions(from.no_unions());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_msgid()) {
      set_msgid(from.msgid());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void NanoPBOptions::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NanoPBOptions::CopyFrom(const NanoPBOptions& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NanoPBOptions::IsInitialized() const {

  return true;
}

void NanoPBOptions::Swap(NanoPBOptions* other) {
  if (other != this) {
    std::swap(max_size_, other->max_size_);
    std::swap(max_count_, other->max_count_);
    std::swap(int_size_, other->int_size_);
    std::swap(type_, other->type_);
    std::swap(long_names_, other->long_names_);
    std::swap(packed_struct_, other->packed_struct_);
    std::swap(skip_message_, other->skip_message_);
    std::swap(no_unions_, other->no_unions_);
    std::swap(msgid_, other->msgid_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata NanoPBOptions::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = NanoPBOptions_descriptor_;
  metadata.reflection = NanoPBOptions_reflection_;
  return metadata;
}

::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::NanoPBOptions >, 11, false >
  nanopb_fileopt(kNanopbFileoptFieldNumber, ::NanoPBOptions::default_instance());
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::NanoPBOptions >, 11, false >
  nanopb_msgopt(kNanopbMsgoptFieldNumber, ::NanoPBOptions::default_instance());
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::NanoPBOptions >, 11, false >
  nanopb_enumopt(kNanopbEnumoptFieldNumber, ::NanoPBOptions::default_instance());
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::NanoPBOptions >, 11, false >
  nanopb(kNanopbFieldNumber, ::NanoPBOptions::default_instance());

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
